name: "GLM-5-AWQ-01"
services:
  vllm:
    image: vllm/vllm-openai:v0.17.1
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #count: all
              device_ids: ['0', '1', '2', '3']
              capabilities: [gpu]
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - /data/models:/data/models:ro
      - ./start.sh:/data/start.sh:ro
      - ./glm4_mtp_fix.py:/data/glm4_mtp_fix.py:ro
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - VLLM_USE_FLASHINFER_MOE_FP16=1
      - VLLM_USE_FLASHINFER_SAMPLER=0
      - OMP_NUM_THREADS=4
      - VLLM_WORKER_MULTIPROC_METHOD=spawn
      - VLLM_MEMORY_EFFICIENT_ATTENTION=1
      - VLLM_USE_MODELSCOPE=false
      - MODELSCOPE_DISABLE_HF_PATCH=1
      - NVIDIA_VISIBLE_DEVICES=all
    entrypoint: "/data/start.sh"
      #entrypoint: "/bin/bash -c 'while true;do sleep 3600;done'"
    # Replace with your model
    ipc: host
